InvolutionPrivateSite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from firstHtml import views as firstviews
from django.conf import settings
from django.views.static import serve
from InvolutionPrivateSite.settings import MEDIA_ROOT

urlpatterns = [
    path('', include('mainSite.urls')),
    path('msggate/', include('msgapp.urls')),
    path('firstHtml/', include('firstHtml.urls')),  # 表示当访问firstHtml/时，去找本地路由
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('home/', firstviews.homeproc),
    path('picture/', firstviews.pictureDownload),
    path('frontMdEditor/', include('frontMdEditor.urls')),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root":MEDIA_ROOT}),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainSite/urls.py
from django.urls import path, re_path
from InvolutionPrivateSite.settings import MEDIA_ROOT
from django.views.static import serve
from . import views

app_name = 'mainSite'

urlpatterns = [
    path('', views.mainProc),
    path('prj/<int:project_id>/', views.prj_detail, name='prj_detail'),
    path('article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('<str:name>/', views.personal_detail, name='personal_detail'),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root":MEDIA_ROOT}),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mainSite/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    project_name = models.CharField(max_length=50)
    project_img = models.ImageField(upload_to = 'prj_img')

    project_theme = models.CharField(max_length=200)
    project_content = models.CharField(max_length=99999)

    pub_date = models.DateTimeField('date published')


# 建立用户数据模型
class UserInfo(models.Model):
    # 建立用户外键
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # 建立用户头像
    user_img = models.ImageField(upload_to = 'user_img')
    # 建立用户简介
    user_intro = models.CharField(max_length=200)

class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    article_name = models.CharField(max_length=50)
    article_img = models.ImageField(upload_to = 'prj_img')

    article_content = models.CharField(max_length=99999)

    pub_date = models.DateTimeField('date published')

mainSite/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from django.http import HttpResponse
from django.utils import timezone
from InvolutionPrivateSite.settings import MEDIA_ROOT
from django.contrib.auth.models import User

from .models import Project, UserInfo, Article


# 用户发布prj数量排名
def prj_rank():
    # 获取用户数量
    user_num = User.objects.all().count()
    # 建立用户发表项目数量的字典
    user_prj_num = {}
    # 统计每个用户发表的项目数量
    for user in User.objects.all():
        user_prj_num[user] = Project.objects.filter(user=user).count()

    # 根据用户发表项目数量从高到底排序
    user_prj_num = sorted(user_prj_num.items(), key=lambda x: x[1], reverse=True)

    # 返回排名前10的用户
    return user_prj_num[:10]

# 主站页面内容替换
def mainProc(request):
    # 再所有模板路径下搜索模板
    template = get_template("mainSite/homePage.html")

    latest_prj = Project.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:1].get()

    # 获取排名前10的用户
    user_prj_num = prj_rank()
    # 根据排名前10的用户，获取用户名字
    user_name = []
    for user in user_prj_num:
        user_name.append(user[0].username)

    # 获取最近的10篇文章
    article_list = Article.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:10]

    # 字典类型，与html文件中的模板语言定义的变量替换
    context = {
        "latest_prj": latest_prj,
        "user_name": user_name,
        "article_list": article_list,
    }

    html = template.render(context)

    return HttpResponse(html)

# 显示项目详情
def prj_detail(request, project_id):
    # 在Project中寻找最新的，未找到则给出404错误
    project = get_object_or_404(Project.objects.filter(pub_date__lte=timezone.now()), pk=project_id)
    userInfo = UserInfo.objects.get(user=project.user)

    # 获取projectPage.html模板，展示项目详情
    template = get_template('mainSite/projectPage.html')
    context = {'project': project, 'userInfo': userInfo}
    response = HttpResponse(template.render(context, request))
    return response

# 显示文章详情
def article_detail(request, article_id):
    # 在Project中寻找最新的，未找到则给出404错误
    article = get_object_or_404(Article.objects.filter(pub_date__lte=timezone.now()), pk=article_id)
    userInfo = UserInfo.objects.get(user=article.user)

    # 获取projectPage.html模板，展示项目详情
    template = get_template('mainSite/articlePage.html')
    context = {'article': article, 'userInfo': userInfo}
    response = HttpResponse(template.render(context, request))
    return response


# 显示个人详情
def personal_detail(request, name):
    # 在User中寻找对应名字，未找到则给出404错误
    user = get_object_or_404(User, username=name)
    userInfo = UserInfo.objects.get(user=user)
    project_list = Project.objects.filter(pub_date__lte=timezone.now(), user=user).order_by('-pub_date')[:10]
    article_list = Article.objects.filter(pub_date__lte=timezone.now(), user=user).order_by('-pub_date')[:10]

    # 获取personalPage.html模板，展示个人详情
    template = get_template('mainSite/personalPage.html')
    context = {
        'user': user,
        'userInfo': userInfo,
        'project_list': project_list,
        'article_list': article_list,
        }
    response = HttpResponse(template.render(context, request))
    return response

mainSite/templates/mainSite/articlePage.html
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8"> 
    <title>个人页面</title> 

    <style type="text/css">
        .articlepic {
            /*基本格式*/
            background-image: url("image/1.jpeg");
            background-size: 100% 100%;
            width: 600px;
            height: 600px;
            /*排版设计*/
            float: left;
            display: inline-block;
            border-radius: 3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;
            text-align:center;
            filter: opacity(0.5);

        }

        .articleinf {
            width: 600px;
            height: 700px;
            display: inline-block;
        }

        .authorpic {
            background-color: #308695;
            width: 600px;
            height: 100px;
            border-radius: 3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;
            text-align:center;
        }

        .articleinformation {
            background-color:#D45769;
            width: 600px;
            height: 350px;
            border-radius:3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;
            text-align:center;
        }

        .enterbutton {
            background-color: #E69D45;
            width: 600px;
            height: 100px;
            border-radius: 50px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;
            text-align:center;
        }
    </style>
</head>

<body style="background-color: #D4CFC9;">
    <div class="articlepic">
    </div>
    <div class="articleinf">
        <div class="authorpic">
            <p><img src="{{MEDIA_URL}}{{ userInfo.user_img }}"></p>
        </div>
        <div class="articleinformation">
            {{ article.article_name }}<br>
            {{ article.pub_date }}<br>
            {{ article.article_content }}<br>
        </div>
        <div class="enterbutton">
            点击进入项目
        </div>
    </div>

</body>

</html>

mainSite/templates/mainSite/homePage.html
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8"> 
    <title>卷友网站</title> 

    <style type="text/css">
        .headerclass {
            background-color: #455054;
            height: 60px;
            display: block;
        }

        .homepageclass {
            background-color: #D4CFC9;
            height: 700px;
            width: 1300px;
            margin:auto;
        }

        .logoclass {
            background-color: #455054;
            height: 40px;
            width: 120px;
            display: inline-block;
            float: left;
            padding-right: 800px;
            text-align: center;
        }

        .mainclass {
            height: 600px;
            width: 840px;
            float: left;
            text-align: center;
            line-height: 300px;
            display: block;
            margin-right: 50px;
        }

        .mainleftclass {
            height: 600px;
            width: 560px;
            float: left;
            display: inline-block;
            border-radius: 3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 0px;
            margin-bottom: 10px;
        }

        .mainlefttopclass {
            background-image: url("image/1.jpeg");
            height: 400px;
            width: 500px;
            float: left;
            border-radius: 3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 0px;
            margin-bottom: 10px;
            filter:opacity(0.5);
        }

        .mainleftbottomclass {
            background-color: #455054;
            height: 100px;
            width: 500px;
            float: left;
            border-radius: 50px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 0px;
            margin-bottom: 10px;
        }

        .mainrightclass {
            background-color: #308695;
            height: 500px;
            width: 260px;
            display: inline-block;
            border-radius: 3px;
            margin-top: 20px;
            margin-left: 0px;
            margin-right: 10px;
            margin-bottom: 10px;
        }

        .searchframeclass {
            background-color: #D4CFC9;
            height: 40px;
            width: 200px;
            display: inline-block;
            text-align: center;
            margin-top: 10px;
        }

        .skillsclass {
            background-color: #E69D45;
            height: 260px;
            width: 300px;
            float: left;
            text-align: center;
            border-radius: 3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;

        }

        .listclass{
            background-color: #D45769;
            height: 260px;
            width: 300px;
            float: left;
            text-align: center;
            border-radius: 3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;
        }



        .viceclass {
            height: 700px;
            width: 300px;
            float: left;
            text-align: center;
            border-radius: 3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;


        }
    </style>
</head>

<body style="background-color: #D4CFC9;">

    <div id="header" class="headerclass">
        <div id="logo" class="logoclass">
            <h5>内卷可视化网站</h5>
        </div>

        <div id="searchframe" class="searchframeclass">
            搜索框</div>
    </div>
    <div id="homepage" class="homepageclass">
        <div id="main" class="mainclass">
            <div class="mainleftclass">
                <div class="mainlefttopclass">
                    {% comment %} <p><img src="{{MEDIA_URL}}{{ latest_prj.project_img }}"></p> {% endcomment %}
                    <p><img src="{{'/media/'}}{{ latest_prj.project_img }}"></p>
                </div>
                <div class="mainleftbottomclass">
                    <ul>
                        <a href="{% url 'mainSite:prj_detail' latest_prj.id %}">{{ latest_prj.project_name }}</a><br>
                    </ul>
                </div>
            </div>
            <div class="mainrightclass">
                {{ latest_prj.project_theme }}<br>
            </div>
        </div>

        <div id="vice" class="viceclass">
            <div id="list" class="listclass">
                用户排名</div>
                {% for name in user_name %}
                <a href="{% url 'mainSite:personal_detail' name %}">{{ name }}</a><br>
                {% endfor %}
            <div id="skills" class="skillsclass">
                实用技巧</div>
                {% for article in article_list %}
                <a href="{% url 'mainSite:article_detail' article.id %}">{{ article.article_name }}</a><br>
                {% endfor %}
        </div>
    </div>
    <div id="tail" class="headerclass">
    </div>
</body>

</html>

mainSite/templates/mainSite/personalPage.html
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8"> 
    <title>个人页面</title> 

    <style type="text/css">
        .personinf {
            width: 400px;
            height:600px;
            display: inline-block;
            float:left;
            border-right: 1px solid #455054;
        }
        .projectinf{
            width: 700px;
            height:600px;
            display:inline-block;
      
        }
        .personalpic{
            background-color: #308695;
            width:300px;
            height:250px;
            border-radius: 3px;
            margin-left: auto;
            margin-right: auto;
            margin-top: auto;
            margin-bottom: auto;
            
        }
        .homepage{
            width:1200px;
            height:600px;
            display:block;
        }
        .pesonalintroduce{
            background-color: #D45769;
            width:300px;
            height:250px;
            border-radius: 3px;
            margin-left: auto;
            margin-right: auto;
            margin-top: auto;
            margin-bottom: auto;
        }
    </style>
</head>

<body style="background-color: #D4CFC9;">
    <div class="homepage">
    <div class="personinf">
        <div class="personalpic">
            <p><img src="{{MEDIA_URL}}{{ userInfo.user_img }}"></p>
        </div>
        <div class="pesonalintroduce">
            <p>{{ userInfo.user_intro }}</p>
        </div>
    </div>
    <div class="projectinf">
        项目列表<br>
        {% for project in project_list %}
        <a href="{% url 'mainSite:prj_detail' project.id %}">{{ project.project_name }}</a><br>
        {% endfor %}

        文章列表<br>
        {% for article in article_list %}
        <a href="{% url 'mainSite:article_detail' article.id %}">{{ article.article_name }}</a><br>
        {% endfor %}
    </div>
    </div>
       
</body>

</html>

mainSite/templates/mainSite/personelPage.html
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8"> 
    <title>个人页面</title> 

    <style type="text/css">
        .personinf {
            width: 400px;
            height:600px;
            display: inline-block;
            float:left;
            border-right: 1px solid #455054;
        }
        .projectinf{
            width: 700px;
            height:600px;
            display:inline-block;
      
        }
        .personalpic{
            background-color: #308695;
            width:300px;
            height:250px;
            border-radius: 3px;
            margin-left: auto;
            margin-right: auto;
            margin-top: auto;
            margin-bottom: auto;
            
        }
        .homepage{
            width:1200px;
            height:600px;
            display:block;
        }
        .pesonalintroduce{
            background-color: #D45769;
            width:300px;
            height:250px;
            border-radius: 3px;
            margin-left: auto;
            margin-right: auto;
            margin-top: auto;
            margin-bottom: auto;
        }
    </style>
</head>

<body style="background-color: #D4CFC9;">
    <div class="homepage">
    <div class="personinf">
        <div class="personalpic">
            <p>个人形象展示</p>
        </div>
        <div class="pesonalintroduce">
            <p>个人文字介绍</p>
        </div>
    </div>
    <div class="projectinf">
        项目列表
    </div>
    </div>
       
</body>

</html>

mainSite/templates/mainSite/projectPage.html
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8"> 
    <title>个人页面</title> 

    <style type="text/css">
        .projectpic {
            /*基本格式*/
            background-image: url("image/1.jpeg");
            background-size: 100% 100%;
            width: 600px;
            height: 600px;
            /*排版设计*/
            float: left;
            display: inline-block;
            border-radius: 3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;
            text-align:center;
            filter: opacity(0.5);

        }

        .projectinf {
            width: 600px;
            height: 700px;
            display: inline-block;
        }

        .authorpic {
            background-color: #308695;
            width: 600px;
            height: 100px;
            border-radius: 3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;
            text-align:center;
        }

        .projectinformation {
            background-color:#D45769;
            width: 600px;
            height: 350px;
            border-radius:3px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;
            text-align:center;
        }

        .enterbutton {
            background-color: #E69D45;
            width: 600px;
            height: 100px;
            border-radius: 50px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 10px;
            text-align:center;
        }
    </style>
</head>

<body style="background-color: #D4CFC9;">
    <div class="projectpic">
    </div>
    <div class="projectinf">
        <div class="authorpic">
            作者头像
        </div>
        <div class="projectinformation">
            {{ project.project_name }}<br>
            {{ project.pubdate }}<br>
            {{ project.project_theme }}<br>
            {{ project.project_content }}<br>
        </div>
        <div class="enterbutton">
            点击进入项目
        </div>
    </div>

</body>

</html>